### ISSUE TITLE
How to setup it in linux?

### ISSUE THREAD

**Issue by vanloc0301** [gabrielgatu/dotfiles#1]
Do I use Ubuntu? How to use `dotfiles` in ubuntu?
Thanks

**Comment by gabrielgatu** [comment]
The guide should work for Mac&Linux, just the installation part of vim should change:

Install Vim:
- "sudo -s"
- "apt-get install vim"

Then:
- Install Vundle Plugin Manager (You need git installed) : "git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle"
- Install Vundle Plugins: "vim +BundleInstall +qall"
- Enable auto-complete (Ubuntu should have python already installed) : 
  "cd ~/.vim/bundle/YouCompleteMe ./install.py --clang-completer"
- Enjoy :)
